language: node_js
node_js:
  - 6.10.0
  - 8
  - 10.0.0
  - node
install:
  - yarn install --production
  - yarn add jest@24.8.0
  - yarn add coveralls@3.0.4
after_success: 'yarn coveralls'
cache:
  yarn: true
  directories:
    - node_modules
